"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.themes = void 0;
const colors_1 = require("./colors");
exports.themes = {
    light: {
        appBackground: colors_1.colors.gray100,
        appBackgroundInverse: colors_1.colors.gray900,
        background: colors_1.colors.white,
        backgroundInverse: colors_1.colors.black,
        elementInteractionBackground: colors_1.colors.white,
        elementInteractionBackgroundInverse: colors_1.colors.black,
        text: colors_1.colors.black,
        textInverse: colors_1.colors.white,
        primary: colors_1.colors.blue500,
        secondary: colors_1.colors.bertiare500,
        success: colors_1.colors.green500,
        successSale: colors_1.colors.green300,
        successSaleHighlight: colors_1.colors.green900,
        warning: colors_1.colors.yellow500,
        warningSale: colors_1.colors.yellow300,
        warningSaleHighlight: colors_1.colors.yellow900,
        danger: colors_1.colors.red500,
        dangerSale: colors_1.colors.red300,
        dangerSaleHighlight: colors_1.colors.red900,
        muted: colors_1.colors.gray400,
        mutedInverse: colors_1.colors.gray200,
        mutedIcon: colors_1.colors.gray100,
        inputBackground: colors_1.colors.white,
        checkboxHover: colors_1.colors.gray500,
        border: colors_1.colors.gray100,
        shadow: colors_1.colors.gray900,
        hoverDepth: colors_1.colors.white,
        accent: colors_1.colors.purple500,
        info: colors_1.colors.cyan500,
    },
    dark: {
        appBackground: colors_1.colors.black,
        appBackgroundInverse: colors_1.colors.gray200,
        background: colors_1.colors.gray900,
        backgroundInverse: colors_1.colors.white,
        elementInteractionBackground: colors_1.colors.black,
        elementInteractionBackgroundInverse: colors_1.colors.white,
        text: colors_1.colors.white,
        textInverse: colors_1.colors.black,
        primary: colors_1.colors.blue300,
        secondary: colors_1.colors.bertiare300,
        success: colors_1.colors.green400,
        successSale: colors_1.colors.green500,
        successSaleHighlight: colors_1.colors.green100,
        warning: colors_1.colors.yellow300,
        warningSale: colors_1.colors.yellow500,
        warningSaleHighlight: colors_1.colors.yellow100,
        danger: colors_1.colors.red300,
        dangerSale: colors_1.colors.red500,
        dangerSaleHighlight: colors_1.colors.red100,
        muted: colors_1.colors.gray500,
        mutedInverse: colors_1.colors.gray400,
        mutedIcon: colors_1.colors.gray700,
        inputBackground: colors_1.colors.black,
        checkboxHover: colors_1.colors.gray400,
        border: colors_1.colors.gray700,
        shadow: colors_1.colors.gray200,
        hoverDepth: colors_1.colors.gray800,
        accent: colors_1.colors.purple300,
        info: colors_1.colors.cyan300,
    },
    solarized: {},
};
